[2024-12-29T00:37:15.797+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-29T00:37:16.149+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_sales_analysis_test.create_table scheduled__2024-12-28T00:00:00+00:00 [queued]>
[2024-12-29T00:37:16.167+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_sales_analysis_test.create_table scheduled__2024-12-28T00:00:00+00:00 [queued]>
[2024-12-29T00:37:16.168+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-29T00:37:16.200+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): create_table> on 2024-12-28 00:00:00+00:00
[2024-12-29T00:37:16.216+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=827) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-29T00:37:16.222+0000] {standard_task_runner.py:72} INFO - Started process 829 to run task
[2024-12-29T00:37:16.226+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_sales_analysis_test', 'create_table', 'scheduled__2024-12-28T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/ecommerse_etl.py', '--cfg-path', '/tmp/tmpch9_al89']
[2024-12-29T00:37:16.232+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask create_table
[2024-12-29T00:37:16.648+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_sales_analysis_test.create_table scheduled__2024-12-28T00:00:00+00:00 [running]> on host 23e56c303c93
[2024-12-29T00:37:16.963+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_sales_analysis_test' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-12-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-28T00:00:00+00:00'
[2024-12-29T00:37:16.970+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-29T00:37:16.971+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-29T00:37:16.973+0000] {logging_mixin.py:190} INFO - Current task name:create_table state:running start_date:2024-12-29 00:37:16.150082+00:00
[2024-12-29T00:37:16.975+0000] {logging_mixin.py:190} INFO - Dag name:etl_sales_analysis_test and current dag run status:running
[2024-12-29T00:37:16.976+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-29T00:37:16.978+0000] {sql.py:278} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS sales_data (
        product_id INT,
        purchase_date DATE,
        total DECIMAL
    );
    
[2024-12-29T00:37:17.005+0000] {base.py:84} INFO - Retrieving connection 'postgres_connection'
[2024-12-29T00:37:17.027+0000] {base.py:84} INFO - Retrieving connection 'postgres_connection'
[2024-12-29T00:37:17.045+0000] {sql.py:553} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS sales_data (
        product_id INT,
        purchase_date DATE,
        total DECIMAL
    );
    , parameters: None
[2024-12-29T00:37:17.090+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-29T00:37:17.091+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_sales_analysis_test, task_id=create_table, run_id=scheduled__2024-12-28T00:00:00+00:00, execution_date=20241228T000000, start_date=20241229T003716, end_date=20241229T003717
[2024-12-29T00:37:17.119+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-29T00:37:17.121+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-29T00:37:17.122+0000] {logging_mixin.py:190} INFO - Dag name:etl_sales_analysis_test queued_at:2024-12-29 00:36:46.792155+00:00
[2024-12-29T00:37:17.122+0000] {logging_mixin.py:190} INFO - Task hostname:23e56c303c93 operator:PostgresOperator
[2024-12-29T00:37:17.162+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-29T00:37:17.212+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-29T00:37:17.216+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
